version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_DB_PASSWORD}
      - MYSQL_DATABASE=${TEST_DB_DATABASE}
      - MYSQL_USER=${TEST_DB_USER}
      - MYSQL_PASSWORD=${TEST_DB_PASSWORD}
      - DB_URL=${TEST_DB_URL}
    networks:
      - database_network

  rest-backend:
    build: 
      context: .
      dockerfile: ./rest-backend/Dockerfile
    command: ["npm", "run", "test"]
    environment:
      - APP_ENV=test
      - DB_URL=${TEST_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - database_network
  
  graphql-backend:
    build: 
      context: .
      dockerfile: ./graphql-backend/Dockerfile
    command: ["npm", "run", "test"]
    environment:
      - APP_ENV=${APP_ENV}
      - DB_URL=${LIVE_DB_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mysql
    networks:
      - database_network

networks:
  database_network:
