name: Run Tests

on:
  push:
    branches:
      - '*'

env:
  DAY_OF_WEEK: Monday
  APP_ENV: dev
  JWT_SECRET: test-secret
  TEST_DB_URL: file:./test.db

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker/compose:1.29.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose -f docker-compose.test.yaml up -d

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.13'

      - name: Install Dependencies
        run: npm ci

      - name: Run graphql-backend Tests
        working-directory: ./graphql-backend
        run: npm test

      - name: Run rest-backend Tests
        working-directory: ./graphql-backend
        run: npm test

      - name: Shut down Docker Compose
        run: docker-compose -f docker-compose.test.yaml down
